platform :ios,'9.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
react_native_path = '../node_modules/react-native'

def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end
# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end

  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save

end

target 'RNWebViewComlink' do
  pod 'FBLazyVector', :path => react_native_path + '/Libraries/FBLazyVector'
  pod 'FBReactNativeSpec', :path => react_native_path + '/Libraries/FBReactNativeSpec'
  pod 'RCTRequired', :path => react_native_path + '/Libraries/RCTRequired'
  pod 'RCTTypeSafety', :path => react_native_path + '/Libraries/TypeSafety'
  pod 'React', :path => react_native_path
  pod 'React-Core', :path => react_native_path
  pod 'React-CoreModules', :path => react_native_path + '/React/CoreModules'
  pod 'React-Core/DevSupport', :path => react_native_path
  pod 'React-Core/RCTWebSocket', :path => react_native_path # needed for debugging

  pod 'React-RCTActionSheet', :path => react_native_path + '/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => react_native_path + '/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => react_native_path + '/Libraries/Blob'
  pod 'React-RCTText', :path => react_native_path + '/Libraries/Text'
  pod 'React-RCTImage',  :path => react_native_path + '/Libraries/Image'
  pod 'React-RCTLinking', :path => react_native_path + '/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => react_native_path + '/Libraries/Network'
  pod 'React-RCTPushNotification', :path => react_native_path + '/Libraries/PushNotificationIOS'
  pod 'React-RCTSettings', :path => react_native_path + '/Libraries/Settings'
  pod 'React-RCTVibration', :path => react_native_path + '/Libraries/Vibration'

  pod 'React-cxxreact', :path => react_native_path + '/ReactCommon/cxxreact'
  pod 'React-jsi', :path => react_native_path + '/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => react_native_path + '/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => react_native_path + '/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => react_native_path + '/ReactCommon'
  pod 'ReactCommon/turbomodule/core', :path => react_native_path + '/ReactCommon'
  pod 'Yoga', :path => react_native_path + '/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
